version: '3.8'

services:
    prod:
        container_name: nesker
        image: nesker:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        environment:
            
            #DATABASE_TYPE: mssql
            #DATABASE_ENCRYPT: false
            #DATABASE_URL: mssql:/SA:mssqlP4$$@192.168.8.130/sysmed
            DATABASE_TYPE: postgres
            DATABASE_ALLOW_SSH: true
            #DATABASE_URL: postgres://postgres:postgres@192.168.8.130/nesker
            DATABASE_URL: postgres://pvufirgquxobic:35a51cdf3894e6f42f4c7018be0bd03405e3af13e551f6dfbc8966c7d970389e@ec2-3-218-171-44.compute-1.amazonaws.com:5432/d2hfiol95a477j

        command: npm run start:prod
        ports:
            - 3000:3000
        network_mode: "host"
        #networks:
        #    - nesker-network
        volumes:
            - .:/api
            - /api/node_modules
        restart: unless-stopped

#networks:
#    nesker-network: